# Generated by Django 3.1.7 on 2021-03-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
