# Generated by Django 3.1.7 on 2021-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
